volumes:
  memos_cafe_local_postgres_data: {}
  memos_cafe_local_postgres_data_backups: {}
  memos_cafe_local_venv: {}


services:
  django:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: memos_cafe_local_django
    container_name: memos_cafe_local_django
    depends_on:
      - postgres
      - redis
    volumes:
      - memos_cafe_local_venv:/app/.venv
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - '8000:8000'
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: memos_cafe_production_postgres
    container_name: memos_cafe_local_postgres
    volumes:
      - memos_cafe_local_postgres_data:/var/lib/postgresql/data
      - memos_cafe_local_postgres_data_backups:/backups
    env_file:
      - ./.envs/.local/.postgres

  redis:
    image: docker.io/redis:7.2
    container_name: memos_cafe_local_redis
