# Generated by Django 6.0.6 on 2026-09-16 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0002_seed_permisos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permisorol',
            name='modulo',
            field=models.CharField(choices=[('dashboard', 'Dashboard'), ('mesas', 'Mesas'), ('ordenes', 'Órdenes'), ('caja', 'Caja'), ('productos', 'Productos'), ('insumos', 'Insumos'), ('reportes', 'Reportes'), ('usuarios', 'Usuarios'), ('ordenes_cocina', 'Cocina — Pedidos')], max_length=50),
        ),
        migrations.AlterField(
            model_name='permisorol',
            name='rol',
            field=models.CharField(choices=[('admin', 'Admin'), ('cajero', 'Cajero'), ('mesero', 'Mesero'), ('cocina', 'Cocina')], max_length=50),
        ),
    ]
