# Generated by Django 6.0.6 on 2026-09-16 07:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mesas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SesionMesaQR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('abierta_en', models.DateTimeField(auto_now_add=True)),
                ('cerrada_en', models.DateTimeField(blank=True, null=True)),
                ('mesa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sesiones_qr', to='mesas.mesa')),
                ('mesero', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sesiones_mesa_abiertas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sesión de mesa (QR)',
                'verbose_name_plural': 'Sesiones de mesa (QR)',
                'db_table': 'sesion_mesa_qr',
                'ordering': ['-abierta_en'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('cerrada_en__isnull', True)), fields=('mesa',), name='una_sesion_activa_por_mesa')],
            },
        ),
    ]
