# Generated by Django 6.0.6 on 2026-09-30 22:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("mesas", "0003_mesa_codigo_qr"),
        ("ordenes", "0007_comandas_existentes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PedidoPorConfirmar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("items", models.JSONField(default=list)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("pendiente", "Por confirmar"),
                            ("confirmado", "Confirmado"),
                            ("rechazado", "Rechazado"),
                            ("expirado", "Expirado"),
                        ],
                        default="pendiente",
                        max_length=12,
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                ("resuelto_en", models.DateTimeField(blank=True, null=True)),
                (
                    "mesa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pedidos_por_confirmar",
                        to="mesas.mesa",
                    ),
                ),
                (
                    "orden",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="ordenes.orden",
                    ),
                ),
                (
                    "resuelto_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pedidos_qr_resueltos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Pedido por confirmar (QR)",
                "verbose_name_plural": "Pedidos por confirmar (QR)",
                "db_table": "pedido_por_confirmar",
                "ordering": ["creado_en"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("estado", "pendiente")),
                        fields=("mesa",),
                        name="un_pedido_por_confirmar_por_mesa",
                    ),
                ],
            },
        ),
    ]
