# Generated by Django 6.0.6 on 2026-09-30 22:06

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("mesas", "0004_pedido_por_confirmar"),
    ]

    operations = [
        migrations.CreateModel(
            name="ElementoPlano",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("barra", "Barra"),
                            ("pared", "Pared o divisor"),
                            ("entrada", "Entrada"),
                            ("texto", "Texto"),
                        ],
                        max_length=10,
                    ),
                ),
                ("etiqueta", models.CharField(blank=True, max_length=40)),
                ("plano_x", models.PositiveSmallIntegerField()),
                ("plano_y", models.PositiveSmallIntegerField()),
                ("plano_ancho", models.PositiveSmallIntegerField()),
                ("plano_alto", models.PositiveSmallIntegerField()),
                (
                    "forma",
                    models.CharField(
                        choices=[
                            ("redonda", "Redonda"),
                            ("rectangular", "Rectangular"),
                        ],
                        default="rectangular",
                        max_length=12,
                    ),
                ),
                ("rotacion", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Elemento del plano",
                "verbose_name_plural": "Elementos del plano",
                "db_table": "elemento_plano",
                "ordering": ["id"],
            },
        ),
        migrations.AddField(
            model_name="mesa",
            name="forma",
            field=models.CharField(
                choices=[("redonda", "Redonda"), ("rectangular", "Rectangular")],
                default="redonda",
                max_length=12,
            ),
        ),
        migrations.AddField(
            model_name="mesa",
            name="plano_alto",
            field=models.PositiveSmallIntegerField(default=70),
        ),
        migrations.AddField(
            model_name="mesa",
            name="plano_ancho",
            field=models.PositiveSmallIntegerField(default=70),
        ),
        migrations.AddField(
            model_name="mesa",
            name="plano_x",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mesa",
            name="plano_y",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mesa",
            name="rotacion",
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
