# Generated by Django 6.0.6 on 2026-09-30 05:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mesas", "0001_initial"),
        ("ordenes", "0003_detalleorden_impreso"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="orden",
            index=models.Index(
                fields=["fecha_creacion"], name="orden_fecha_creacion_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="orden",
            index=models.Index(fields=["fecha_cierre"], name="orden_fecha_cierre_idx"),
        ),
        migrations.AddIndex(
            model_name="orden",
            index=models.Index(
                condition=models.Q(("estado", "abierta")),
                fields=["fecha_creacion"],
                name="orden_abiertas_idx",
            ),
        ),
    ]
