# Generated by Django 6.0.6 on 2026-09-30 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ordenes", "0004_detalleorden_estado_preparacion_ronda"),
        ("ordenes", "0004_indices_fechas"),
    ]

    operations = []
