# Generated by Django 6.0.6 on 2026-09-30 21:54

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("ordenes", "0005_merge_indices_fechas_estado_preparacion"),
    ]

    operations = [
        migrations.CreateModel(
            name="Comanda",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero", models.PositiveSmallIntegerField()),
                (
                    "origen",
                    models.CharField(
                        choices=[("mesero", "Mesero"), ("qr", "Pedido por QR")],
                        default="mesero",
                        max_length=10,
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente"),
                            ("en_preparacion", "En preparación"),
                            ("lista", "Lista"),
                            ("entregada", "Entregada"),
                        ],
                        default="pendiente",
                        max_length=15,
                    ),
                ),
                ("creada_en", models.DateTimeField(auto_now_add=True)),
                ("iniciada_en", models.DateTimeField(blank=True, null=True)),
                ("lista_en", models.DateTimeField(blank=True, null=True)),
                ("entregada_en", models.DateTimeField(blank=True, null=True)),
                (
                    "orden",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comandas",
                        to="ordenes.orden",
                    ),
                ),
            ],
            options={
                "verbose_name": "Comanda",
                "verbose_name_plural": "Comandas",
                "db_table": "comanda",
                "ordering": ["creada_en"],
            },
        ),
        migrations.AddField(
            model_name="detalleorden",
            name="comanda",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="detalles",
                to="ordenes.comanda",
            ),
        ),
        migrations.AddConstraint(
            model_name="comanda",
            constraint=models.UniqueConstraint(
                fields=("orden", "numero"),
                name="comanda_numero_unico_por_orden",
            ),
        ),
    ]
