# Generated by Django 6.0.6 on 2026-09-16 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0005_notacredito'),
        ('ordenes', '0004_detalleorden_estado_preparacion_ronda'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudCobro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodo_pago_sugerido', models.CharField(choices=[('efectivo', 'Efectivo'), ('tarjeta', 'Tarjeta'), ('yape', 'Yape'), ('plin', 'Plin')], max_length=10)),
                ('solicitado_en', models.DateTimeField(auto_now_add=True)),
                ('atendido_en', models.DateTimeField(blank=True, null=True)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes_cobro', to='ordenes.orden')),
            ],
            options={
                'verbose_name': 'Solicitud de cobro',
                'verbose_name_plural': 'Solicitudes de cobro',
                'db_table': 'solicitud_cobro',
                'ordering': ['-solicitado_en'],
            },
        ),
    ]
