# Generated by Django 6.0.6 on 2026-09-30 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("caja", "0005_notacredito"),
        ("ordenes", "0003_detalleorden_impreso"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="pago",
            index=models.Index(fields=["fecha"], name="pago_fecha_idx"),
        ),
    ]
