# Generated by Django 6.0.6 on 2026-09-30 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("caja", "0006_indices_fechas"),
        ("caja", "0006_solicitudcobro"),
    ]

    operations = []
